name: Action

on:
  workflow_call:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.14"

jobs:
  action_hook:
    runs-on: ubuntu-latest
    name: Docstring Linter
    steps:
      - uses: actions/checkout@v7
        name: Git Checkout

      - uses: actions/setup-python@v6
        name: Install Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: bastgau/docstring-linter@main
        name: Execute Docstring Linter via GitHub Action
        with:
          paths: src/
          format: github-annotations

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install prek
        run: uv tool install prek

      - name: Execute Docstring Linter via Prek
        run: prek run --config .pre-commit-config-hook.yaml --all-files
