name: Main - Code, Quality & Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    name: Lint

  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml
    name: Tests
    secrets: inherit

  build:
    needs: tests
    uses: ./.github/workflows/build.yml
    name: Build

  action:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/action.yml
    name: Action
